const { withGradleProperties } = require('expo/config-plugins');
const { execFileSync } = require('child_process');

/**
 * Pins the JDK that Gradle runs on.
 *
 * React Native 0.86 / AGP require JDK 17+, but a machine whose default `java`
 * is older fails with "Gradle requires JVM 17 or later". Setting JAVA_HOME in
 * the shell fixes it only for interactive runs — `expo run:android` spawns
 * Gradle itself and may not inherit it.
 *
 * `android/` is gitignored and regenerated by `expo prebuild`, so editing
 * gradle.properties by hand does not survive. This plugin re-applies the pin
 * on every prebuild.
 *
 * Resolution order:
 *   1. EXPO_ANDROID_JAVA_HOME (explicit override, e.g. in CI)
 *   2. `/usr/libexec/java_home -v 17` on macOS
 *   3. no pin — fall back to whatever Gradle finds
 */
function resolveJdk17() {
  if (process.env.EXPO_ANDROID_JAVA_HOME) {
    return process.env.EXPO_ANDROID_JAVA_HOME;
  }

  if (process.platform !== 'darwin') return null;

  try {
    return execFileSync('/usr/libexec/java_home', ['-v', '17'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    // No JDK 17 installed; leave Gradle to its own discovery so the build
    // fails with Gradle's own actionable message rather than a bad path.
    return null;
  }
}

const withJdkPin = (config) => {
  return withGradleProperties(config, (gradleConfig) => {
    const javaHome = resolveJdk17();
    if (!javaHome) return gradleConfig;

    const key = 'org.gradle.java.home';
    const properties = gradleConfig.modResults.filter(
      (item) => !(item.type === 'property' && item.key === key),
    );

    properties.push({
      type: 'comment',
      value: 'JDK 17+ is required by React Native 0.86 / AGP. Pinned by plugins/withJdkPin.js',
    });
    properties.push({ type: 'property', key, value: javaHome });

    gradleConfig.modResults = properties;
    return gradleConfig;
  });
};

module.exports = withJdkPin;
